### ISSUE TITLE
Error when starting OxyTown

### ISSUE THREAD

**Issue by alexwilliamlex** [Oxywire/OxyTowns#5]
### Before Submitting

- [X] I am on the latest version of the plugin.
- [X] I have searched for existing issues

### Describe The Bug.

hello, I bought your plugin. I put it in my server when I start the server the plugin does not activate and here are the errors: 
Update link log : https://mclo.gs/UhYxis1

### Expected Behavior

it starts

### Steps To Reproduce

.

### OxyTowns Version

v1.0.5

### Server Version

1.20.4

**Comment by SirSalad** [comment]
The default config ships for 1.21, but it can be modified for 1.20 by changing
- `MOOSHROOM` -> `MUSHROOM_COW`
- `SNOW_GOLEM` -> `SNOWMAN`
